[[redirects]]
from = "/"
to = "/fr"
status = 301
force = false
conditions = {Language = ["fr"]}

[[redirects]]
from = "/"
to = "/lu"
status = 301
force = false
conditions = {Language = ["lu"]}

[[redirects]]
from = "/"
to = "/en"
status = 301
force = false